#!/bin/bash

# manking start files executable
chmod +x ~/binder/start.mysql 
chmod +x ~/binder/start.mariadb 
chmod +x ~/binder/start.vscode 


# starting mysql or mariadb in parallel
~/binder/start.mariadb   &
# ~/binder/start.mysql   &

# executing vscode-related startup commands
~/binder/start.vscode   &

# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"